import { Figtree, Space_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-space-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-figtree",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceMono.variable} ${figtree.variable}`}>
      <body className="font-sans">{children}</body>
    </html>
  );
}
